use_cuda: True
dataset: 'kspon'
dataset_path: ''
transcripts_path: 'data/eval_transcript.txt'
model_path: ''
output_unit: 'character'
batch_size: 128
num_workers: 8
print_every: 20
decode: 'greedy'
k: 3